spring.application.name=phonepay
server.port=9091

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/phonepay}
spring.data.mongodb.database=phonepay

spring.jackson.serialization.write-dates-as-timestamps=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
